server:
  port: 8081
spring:
  application:
    name: alipay-server
  datasource:
    url: jdbc:mysql://localhost:3306/alipay?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.25.139
    port: 5672
    username: guest
    password: guest
    virtual-host: /
mybatis:
  configuration:
    map-underscore-to-camel-case: true
